version: '3.8'
services:
  app:
    build:
      context: .
      target: production
      args:
        PRIMARY_DB_URL: ${PRIMARY_DB_URL}
        PRIMARY_DB_DRIVER: ${PRIMARY_DB_DRIVER}
        PRIMARY_DB_USER: ${PRIMARY_DB_USER}
        PRIMARY_DB_PASSWORD: ${PRIMARY_DB_PASSWORD}
        SECONDARY_DB_URL: ${SECONDARY_DB_URL}
        JPA_DIALECT: ${JPA_DIALECT}
        SEC_USER_PASSWORD: ${SEC_USER_PASSWORD}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        AWS_REGION: ${AWS_REGION}
        S3_BUCKET: ${S3_BUCKET}
    ports:
      - "80:8080"
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
